import { Inter } from "next/font/google";
import { GlobalLayout } from '../components/GlobalLayout';
import "./globals.css";
import "./reset.css"
import AuthProvider from "@/context/AuthProvider";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="ko">


      <head>
        <script
          type="text/javascript"
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d683e5649f857f0f8303b8b30652e395&libraries=services,clusterer"
        ></script>
      </head>
      <AuthProvider>
        <body className={inter.className}>
          <GlobalLayout>
            {children}
          </GlobalLayout>
        </body>
      </AuthProvider>
    </html>
  );
}


